apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestator-ms
  template:
    metadata:
      labels:
        app: orchestator-ms
    spec:
      containers:
        - name: orchestator-ms-container
          image: ghcr.io/mayik81git/orchestator-ms:latest # Â¡VERIFICA EL NOMBRE DE TU REPO AQUI!
          ports:
            - containerPort: 8083
          env:
            # Variables para el despliegue en K8s (Docker Desktop local)
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://host.docker.internal:5432/testdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "admin"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "admin"
            - name: SPRING_RABBITMQ_HOST
              value: "host.docker.internal"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"