apiVersion: v1
kind: Service
metadata:
  name: orchestator-ms-service
spec:
  selector:
    app: orchestator-ms # Debe coincidir con el label del Deployment
  ports:
    - protocol: TCP
      port: 80 # Puerto del Service
      targetPort: 8083 # Puerto real de la aplicaci√≥n